name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Code auschecken
      uses: actions/checkout@v4
      
    - name: Python installieren
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Dependencies installieren
      run: |
        pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Tests ausführen
      run: pytest -v
